// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ai_analysis.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sentiment int32

const (
	Sentiment_SENTIMENT_UNSPECIFIED Sentiment = 0
	Sentiment_SENTIMENT_BULLISH     Sentiment = 1
	Sentiment_SENTIMENT_BEARISH     Sentiment = 2
	Sentiment_SENTIMENT_NEUTRAL     Sentiment = 3
)

// Enum value maps for Sentiment.
var (
	Sentiment_name = map[int32]string{
		0: "SENTIMENT_UNSPECIFIED",
		1: "SENTIMENT_BULLISH",
		2: "SENTIMENT_BEARISH",
		3: "SENTIMENT_NEUTRAL",
	}
	Sentiment_value = map[string]int32{
		"SENTIMENT_UNSPECIFIED": 0,
		"SENTIMENT_BULLISH":     1,
		"SENTIMENT_BEARISH":     2,
		"SENTIMENT_NEUTRAL":     3,
	}
)

func (x Sentiment) Enum() *Sentiment {
	p := new(Sentiment)
	*p = x
	return p
}

func (x Sentiment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sentiment) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_analysis_proto_enumTypes[0].Descriptor()
}

func (Sentiment) Type() protoreflect.EnumType {
	return &file_ai_analysis_proto_enumTypes[0]
}

func (x Sentiment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sentiment.Descriptor instead.
func (Sentiment) EnumDescriptor() ([]byte, []int) {
	return file_ai_analysis_proto_rawDescGZIP(), []int{0}
}

type RiskLevel int32

const (
	RiskLevel_RISK_LEVEL_UNSPECIFIED RiskLevel = 0
	RiskLevel_RISK_LEVEL_LOW         RiskLevel = 1
	RiskLevel_RISK_LEVEL_MEDIUM      RiskLevel = 2
	RiskLevel_RISK_LEVEL_HIGH        RiskLevel = 3
)

// Enum value maps for RiskLevel.
var (
	RiskLevel_name = map[int32]string{
		0: "RISK_LEVEL_UNSPECIFIED",
		1: "RISK_LEVEL_LOW",
		2: "RISK_LEVEL_MEDIUM",
		3: "RISK_LEVEL_HIGH",
	}
	RiskLevel_value = map[string]int32{
		"RISK_LEVEL_UNSPECIFIED": 0,
		"RISK_LEVEL_LOW":         1,
		"RISK_LEVEL_MEDIUM":      2,
		"RISK_LEVEL_HIGH":        3,
	}
)

func (x RiskLevel) Enum() *RiskLevel {
	p := new(RiskLevel)
	*p = x
	return p
}

func (x RiskLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_analysis_proto_enumTypes[1].Descriptor()
}

func (RiskLevel) Type() protoreflect.EnumType {
	return &file_ai_analysis_proto_enumTypes[1]
}

func (x RiskLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskLevel.Descriptor instead.
func (RiskLevel) EnumDescriptor() ([]byte, []int) {
	return file_ai_analysis_proto_rawDescGZIP(), []int{1}
}

type AiAnalysis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Ticker        string                 `protobuf:"bytes,2,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Sentiment     Sentiment              `protobuf:"varint,4,opt,name=sentiment,proto3,enum=proto.Sentiment" json:"sentiment,omitempty"`
	RiskLevel     RiskLevel              `protobuf:"varint,5,opt,name=risk_level,json=riskLevel,proto3,enum=proto.RiskLevel" json:"risk_level,omitempty"`
	ModelUsed     string                 `protobuf:"bytes,6,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	LatencyMs     int32                  `protobuf:"varint,7,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiAnalysis) Reset() {
	*x = AiAnalysis{}
	mi := &file_ai_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiAnalysis) ProtoMessage() {}

func (x *AiAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_ai_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiAnalysis.ProtoReflect.Descriptor instead.
func (*AiAnalysis) Descriptor() ([]byte, []int) {
	return file_ai_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *AiAnalysis) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AiAnalysis) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *AiAnalysis) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AiAnalysis) GetSentiment() Sentiment {
	if x != nil {
		return x.Sentiment
	}
	return Sentiment_SENTIMENT_UNSPECIFIED
}

func (x *AiAnalysis) GetRiskLevel() RiskLevel {
	if x != nil {
		return x.RiskLevel
	}
	return RiskLevel_RISK_LEVEL_UNSPECIFIED
}

func (x *AiAnalysis) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *AiAnalysis) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

var File_ai_analysis_proto protoreflect.FileDescriptor

const file_ai_analysis_proto_rawDesc = "" +
	"\n" +
	"\x11ai_analysis.proto\x12\x05proto\"\x84\x02\n" +
	"\n" +
	"AiAnalysis\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x16\n" +
	"\x06ticker\x18\x02 \x01(\tR\x06ticker\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12.\n" +
	"\tsentiment\x18\x04 \x01(\x0e2\x10.proto.SentimentR\tsentiment\x12/\n" +
	"\n" +
	"risk_level\x18\x05 \x01(\x0e2\x10.proto.RiskLevelR\triskLevel\x12\x1d\n" +
	"\n" +
	"model_used\x18\x06 \x01(\tR\tmodelUsed\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\a \x01(\x05R\tlatencyMs*k\n" +
	"\tSentiment\x12\x19\n" +
	"\x15SENTIMENT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SENTIMENT_BULLISH\x10\x01\x12\x15\n" +
	"\x11SENTIMENT_BEARISH\x10\x02\x12\x15\n" +
	"\x11SENTIMENT_NEUTRAL\x10\x03*g\n" +
	"\tRiskLevel\x12\x1a\n" +
	"\x16RISK_LEVEL_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eRISK_LEVEL_LOW\x10\x01\x12\x15\n" +
	"\x11RISK_LEVEL_MEDIUM\x10\x02\x12\x13\n" +
	"\x0fRISK_LEVEL_HIGH\x10\x03B6Z4github.com/Fahmi-mi/equisentinel/gateway/proto;protob\x06proto3"

var (
	file_ai_analysis_proto_rawDescOnce sync.Once
	file_ai_analysis_proto_rawDescData []byte
)

func file_ai_analysis_proto_rawDescGZIP() []byte {
	file_ai_analysis_proto_rawDescOnce.Do(func() {
		file_ai_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_analysis_proto_rawDesc), len(file_ai_analysis_proto_rawDesc)))
	})
	return file_ai_analysis_proto_rawDescData
}

var file_ai_analysis_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ai_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ai_analysis_proto_goTypes = []any{
	(Sentiment)(0),     // 0: proto.Sentiment
	(RiskLevel)(0),     // 1: proto.RiskLevel
	(*AiAnalysis)(nil), // 2: proto.AiAnalysis
}
var file_ai_analysis_proto_depIdxs = []int32{
	0, // 0: proto.AiAnalysis.sentiment:type_name -> proto.Sentiment
	1, // 1: proto.AiAnalysis.risk_level:type_name -> proto.RiskLevel
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ai_analysis_proto_init() }
func file_ai_analysis_proto_init() {
	if File_ai_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_analysis_proto_rawDesc), len(file_ai_analysis_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_analysis_proto_goTypes,
		DependencyIndexes: file_ai_analysis_proto_depIdxs,
		EnumInfos:         file_ai_analysis_proto_enumTypes,
		MessageInfos:      file_ai_analysis_proto_msgTypes,
	}.Build()
	File_ai_analysis_proto = out.File
	file_ai_analysis_proto_goTypes = nil
	file_ai_analysis_proto_depIdxs = nil
}
