// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: anomaly_event.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnomalyEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId  string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Ticker         string                 `protobuf:"bytes,2,opt,name=ticker,proto3" json:"ticker,omitempty"`
	TriggerType    string                 `protobuf:"bytes,3,opt,name=trigger_type,json=triggerType,proto3" json:"trigger_type,omitempty"`
	PriceChangePct float64                `protobuf:"fixed64,4,opt,name=price_change_pct,json=priceChangePct,proto3" json:"price_change_pct,omitempty"`
	VolumeRatio    float64                `protobuf:"fixed64,5,opt,name=volume_ratio,json=volumeRatio,proto3" json:"volume_ratio,omitempty"`
	DetectedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnomalyEvent) Reset() {
	*x = AnomalyEvent{}
	mi := &file_anomaly_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnomalyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnomalyEvent) ProtoMessage() {}

func (x *AnomalyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_anomaly_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnomalyEvent.ProtoReflect.Descriptor instead.
func (*AnomalyEvent) Descriptor() ([]byte, []int) {
	return file_anomaly_event_proto_rawDescGZIP(), []int{0}
}

func (x *AnomalyEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AnomalyEvent) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *AnomalyEvent) GetTriggerType() string {
	if x != nil {
		return x.TriggerType
	}
	return ""
}

func (x *AnomalyEvent) GetPriceChangePct() float64 {
	if x != nil {
		return x.PriceChangePct
	}
	return 0
}

func (x *AnomalyEvent) GetVolumeRatio() float64 {
	if x != nil {
		return x.VolumeRatio
	}
	return 0
}

func (x *AnomalyEvent) GetDetectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DetectedAt
	}
	return nil
}

var File_anomaly_event_proto protoreflect.FileDescriptor

const file_anomaly_event_proto_rawDesc = "" +
	"\n" +
	"\x13anomaly_event.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfa\x01\n" +
	"\fAnomalyEvent\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x16\n" +
	"\x06ticker\x18\x02 \x01(\tR\x06ticker\x12!\n" +
	"\ftrigger_type\x18\x03 \x01(\tR\vtriggerType\x12(\n" +
	"\x10price_change_pct\x18\x04 \x01(\x01R\x0epriceChangePct\x12!\n" +
	"\fvolume_ratio\x18\x05 \x01(\x01R\vvolumeRatio\x12;\n" +
	"\vdetected_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"detectedAtB6Z4github.com/Fahmi-mi/equisentinel/gateway/proto;protob\x06proto3"

var (
	file_anomaly_event_proto_rawDescOnce sync.Once
	file_anomaly_event_proto_rawDescData []byte
)

func file_anomaly_event_proto_rawDescGZIP() []byte {
	file_anomaly_event_proto_rawDescOnce.Do(func() {
		file_anomaly_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anomaly_event_proto_rawDesc), len(file_anomaly_event_proto_rawDesc)))
	})
	return file_anomaly_event_proto_rawDescData
}

var file_anomaly_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_anomaly_event_proto_goTypes = []any{
	(*AnomalyEvent)(nil),          // 0: proto.AnomalyEvent
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_anomaly_event_proto_depIdxs = []int32{
	1, // 0: proto.AnomalyEvent.detected_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_anomaly_event_proto_init() }
func file_anomaly_event_proto_init() {
	if File_anomaly_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anomaly_event_proto_rawDesc), len(file_anomaly_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_anomaly_event_proto_goTypes,
		DependencyIndexes: file_anomaly_event_proto_depIdxs,
		MessageInfos:      file_anomaly_event_proto_msgTypes,
	}.Build()
	File_anomaly_event_proto = out.File
	file_anomaly_event_proto_goTypes = nil
	file_anomaly_event_proto_depIdxs = nil
}
