// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: news_article.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewsArticle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ticker        string                 `protobuf:"bytes,2,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Headline      string                 `protobuf:"bytes,3,opt,name=headline,proto3" json:"headline,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewsArticle) Reset() {
	*x = NewsArticle{}
	mi := &file_news_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsArticle) ProtoMessage() {}

func (x *NewsArticle) ProtoReflect() protoreflect.Message {
	mi := &file_news_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsArticle.ProtoReflect.Descriptor instead.
func (*NewsArticle) Descriptor() ([]byte, []int) {
	return file_news_article_proto_rawDescGZIP(), []int{0}
}

func (x *NewsArticle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NewsArticle) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *NewsArticle) GetHeadline() string {
	if x != nil {
		return x.Headline
	}
	return ""
}

func (x *NewsArticle) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NewsArticle) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *NewsArticle) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

var File_news_article_proto protoreflect.FileDescriptor

const file_news_article_proto_rawDesc = "" +
	"\n" +
	"\x12news_article.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbc\x01\n" +
	"\vNewsArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06ticker\x18\x02 \x01(\tR\x06ticker\x12\x1a\n" +
	"\bheadline\x18\x03 \x01(\tR\bheadline\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12=\n" +
	"\fpublished_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAtB6Z4github.com/Fahmi-mi/equisentinel/gateway/proto;protob\x06proto3"

var (
	file_news_article_proto_rawDescOnce sync.Once
	file_news_article_proto_rawDescData []byte
)

func file_news_article_proto_rawDescGZIP() []byte {
	file_news_article_proto_rawDescOnce.Do(func() {
		file_news_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_news_article_proto_rawDesc), len(file_news_article_proto_rawDesc)))
	})
	return file_news_article_proto_rawDescData
}

var file_news_article_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_news_article_proto_goTypes = []any{
	(*NewsArticle)(nil),           // 0: proto.NewsArticle
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_news_article_proto_depIdxs = []int32{
	1, // 0: proto.NewsArticle.published_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_news_article_proto_init() }
func file_news_article_proto_init() {
	if File_news_article_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_news_article_proto_rawDesc), len(file_news_article_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_news_article_proto_goTypes,
		DependencyIndexes: file_news_article_proto_depIdxs,
		MessageInfos:      file_news_article_proto_msgTypes,
	}.Build()
	File_news_article_proto = out.File
	file_news_article_proto_goTypes = nil
	file_news_article_proto_depIdxs = nil
}
