// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: stock_quote.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockQuote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Open          float64                `protobuf:"fixed64,2,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,3,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,4,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,5,opt,name=close,proto3" json:"close,omitempty"`
	Volume        int64                  `protobuf:"varint,6,opt,name=volume,proto3" json:"volume,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockQuote) Reset() {
	*x = StockQuote{}
	mi := &file_stock_quote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockQuote) ProtoMessage() {}

func (x *StockQuote) ProtoReflect() protoreflect.Message {
	mi := &file_stock_quote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockQuote.ProtoReflect.Descriptor instead.
func (*StockQuote) Descriptor() ([]byte, []int) {
	return file_stock_quote_proto_rawDescGZIP(), []int{0}
}

func (x *StockQuote) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *StockQuote) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *StockQuote) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *StockQuote) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *StockQuote) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *StockQuote) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *StockQuote) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_stock_quote_proto protoreflect.FileDescriptor

const file_stock_quote_proto_rawDesc = "" +
	"\n" +
	"\x11stock_quote.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc6\x01\n" +
	"\n" +
	"StockQuote\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x12\x12\n" +
	"\x04open\x18\x02 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x03 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x04 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x05 \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\x03R\x06volume\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB6Z4github.com/Fahmi-mi/equisentinel/gateway/proto;protob\x06proto3"

var (
	file_stock_quote_proto_rawDescOnce sync.Once
	file_stock_quote_proto_rawDescData []byte
)

func file_stock_quote_proto_rawDescGZIP() []byte {
	file_stock_quote_proto_rawDescOnce.Do(func() {
		file_stock_quote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stock_quote_proto_rawDesc), len(file_stock_quote_proto_rawDesc)))
	})
	return file_stock_quote_proto_rawDescData
}

var file_stock_quote_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_stock_quote_proto_goTypes = []any{
	(*StockQuote)(nil),            // 0: proto.StockQuote
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_stock_quote_proto_depIdxs = []int32{
	1, // 0: proto.StockQuote.timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stock_quote_proto_init() }
func file_stock_quote_proto_init() {
	if File_stock_quote_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stock_quote_proto_rawDesc), len(file_stock_quote_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stock_quote_proto_goTypes,
		DependencyIndexes: file_stock_quote_proto_depIdxs,
		MessageInfos:      file_stock_quote_proto_msgTypes,
	}.Build()
	File_stock_quote_proto = out.File
	file_stock_quote_proto_goTypes = nil
	file_stock_quote_proto_depIdxs = nil
}
